# Generated by Django 4.2.6 on 2023-10-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchAndFilters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filters',
            new_name='Books',
        ),
    ]
