# Generated by Django 4.2.6 on 2023-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('bookformat', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('isbn13', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('totalratings', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
