# Generated by Django 4.2.6 on 2023-10-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231029_1436'),
        ('main', '0002_book_status_book_user_avg_rating'),
    ]

    operations = [
    ]
