# Generated by Django 4.2.6 on 2023-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_book_totalratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='totalratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
