# Generated by Django 4.2.6 on 2023-10-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20231029_0927'),
        ('main', '0005_book_totalratings'),
    ]

    operations = [
    ]
