# Generated by Django 4.2.6 on 2023-10-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_user'),
        ('myLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
